"""add merchant field to payment model

Revision ID: 338ef67c19cc
Revises: b366a305d2ab
Create Date: 2023-09-10 19:57:19.778489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '338ef67c19cc'
down_revision: Union[str, None] = 'b366a305d2ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('merchant', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'merchant')
    # ### end Alembic commands ###
