"""add payment_url field to topup model

Revision ID: 3aaf89855e71
Revises: ed576e68bd7a
Create Date: 2023-09-11 00:23:52.062473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aaf89855e71'
down_revision: Union[str, None] = 'ed576e68bd7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topups', sa.Column('payment_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topups', 'payment_url')
    # ### end Alembic commands ###
