"""add merchant field to payment model

Revision ID: b366a305d2ab
Revises: 9513867a97e2
Create Date: 2023-09-10 19:54:02.392783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b366a305d2ab'
down_revision: Union[str, None] = '9513867a97e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('merchant', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'merchant')
    # ### end Alembic commands ###
