"""add api_key field to use model

Revision ID: ed576e68bd7a
Revises: 338ef67c19cc
Create Date: 2023-09-10 23:46:13.645040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed576e68bd7a'
down_revision: Union[str, None] = '338ef67c19cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('api_key', sa.String(), nullable=True))
    op.add_column('users', sa.Column('api_test_key', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['api_key'])
    op.create_unique_constraint(None, 'users', ['api_test_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'api_test_key')
    op.drop_column('users', 'api_key')
    # ### end Alembic commands ###
